Support GO 710; support swap and minix partitions; fix suspend, bluetooth

diff --git a/src/opentom_skel/bin/start_bt b/src/opentom_skel/bin/start_bt
--- a/src/opentom_skel/bin/start_bt
+++ b/src/opentom_skel/bin/start_bt
@@ -1,56 +1,29 @@
 #! /bin/sh
 
-if ls -l /dev/bt 2>/dev/null; then
-	echo Bluetooth system allready initialised
-	exit 1
-fi
+# Start bluetooth device, files and services
 
-# Defaults
-csrinit="y"
-btdev="/dev/bt"
-btif="hci0"
-btmulaw="0"
+btdev=/dev/bt
+btif=hci0
 
-mkdir -p /etc/bluetooth/
+die() { echo "$*" 1>&2 ; exit 1; }
 
-# Setup variables to be inherited by called shell scripts
-for i in /proc/barcelona/*; do
-      export hw_${i##*/}="$(cat $i)"
-done
-if test -n "${hw_gpsdev}"; then
-    ln -sf "${hw_gpsdev}" /dev/gpsdata
-fi
-if test -n "${hw_btdev}"; then
-    ln -sf "${hw_btdev}" /dev/bt
-fi
-if test -n "${hw_gprsmodemdev}"; then
-    ln -sf "${hw_gprsmodemdev}" /dev/gprsmodem
-fi
+do_csrinit() { cmd="$1"; shift; csrinit "$cmd" "$btdev" "$hw_btspeed" "$hw_btclock" $@ 2>&1; }
 
+ls -l "$btdev" 2>/dev/null && die 'Bluetooth system already initialized'
 
-if ! sed "s/@DEVNAME@/${hw_btname}/;s/@DEVCLASS@/${hw_btclass}/" \
-	$HOME/etc/hcid.conf.template > /etc/bluetooth/hcid.conf; then
-    die "unable to setup hcid config file"
-fi
+[ "$hw_btdev" ] && ln -sf "$hw_btdev" "$btdev"
 
-if test "${csrinit}" = "y"; then
-  if test "${hw_btusb}" = "0"; then
-    if ! csrinit bcsp ${btdev} ${hw_btspeed} ${hw_btclock}; then
-      die "csrinit failed"
-    fi
-  elif ! csrinit usb ${btdev} ${hw_btspeed} ${hw_btclock}; then
-    echo "csrinit usb failed, trying bcsp"
-    if ! csrinit bcsp ${btdev} ${hw_btspeed} ${hw_btclock}; then
-      die "csrinit bcsp failed too"
-    fi
-  fi
-fi
+[ -f "$DIST/etc/bluetooth/pin" ] && ! cp -f "$DIST/etc/bluetooth/pin" /etc/bluetooth/ && die 'unable to copy pin file'; }
 
+sed "s/@DEVNAME@/$hw_btname/;s/@DEVCLASS@/$(printf "0x%06x" "$hw_btclass")/" "$DIST/etc/hcid.conf.template" >/etc/bluetooth/hcid.conf 2>/dev/null ||
+	die 'unable to setup hcid config file'
 
-if test "${hw_btusb}" = "0" && ! hciattach /dev/bt bcsp ${hw_btspeed}; then
-  die "hciattach failed"
-fi
+[ "$hw_btusb" = "1" ] && { do_csrinit usb || ! echo 'csrinit usb failed, trying bcsp'; } || do_csrinit bcsp || die 'csrinit bcsp failed'
 
-if ! hciconfig ${btif} up; then
-  die "hciconfig failed"
-fi
+hcid || die 'hcid failed'
+
+hciattach "$btdev" bcsp "$hw_btspeed" || die 'hciattach failed'
+
+sdpd || die 'sdpd failed'
+
+hciconfig "$btif" up
